<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Yeo Hang Out</title>
<!-- Bootstrap core CSS -->
<link href="assets/css/bootstrap.min.css" rel="stylesheet">

<!-- Custom styles for this template -->
<link href="assets/css/dashboard.css" rel="stylesheet">
<link rel="stylesheet" type="text/css"
	href="assets/css/datatables.min.css" />
<link href="assets/css/search.css" rel="stylesheet">
<link rel="stylesheet" href="assets/css/bootstrap-datetimepicker.min.css" /> <!-- Bootstrap DTP CSS -->
<link rel="stylesheet" href="assets/css/font-awesome.min.css">

</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed"
					data-toggle="collapse" data-target="#navbar" aria-expanded="false"
					aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="../index.jsp">Yeo Hang Out</a>
			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="../index.jsp">HOME</a></li>
					<li><a href="#">SETTINGS</a></li>
					<li><a href="#">LOG OUT</a></li>
					<li><a href="#">HELP</a></li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="container-fluid text-center">
		<br>
		<br>
		<br>
		<br>
		<h1>This is a <b class="bg-red no-wrap"><%//Airline Name %>HELP</b> <span class="no-wrap">Page</span></h1>
		<i class="fa fa-info-circle fa-5x times bg-red" aria-hidden="true"></i>
		<br>
		<div class="row">
			<h2>How to Use:</h2>
			To use, Log-In through upper navigation bar by clicking 'Log In'.
			<br> If you don't have an account, Sign-Up through upper navigation
			bar by clicking 'Sign In'.
			<br> Everything is fully-responsive. You can view this web site in
			any devices with fully-optimized resolutions.
			<h3>For manager:</h3> Add, Edit and Delete information for an employee
			<br> Obtain a sales report for a particular month
			<br> Produce a comprehensive listing of all flights
			<br> Produce a list of reservations by flight number or by customer
			name
			<br> Produce a summary listing of revenue generated by a particular
			flight, destination city, or customer
			<br> Determine which customer representative generated most total
			revenue
			<br> Determine which customer generated most total revenue
			<br> Produce a list of most active flights
			<br> Produce a list of all customers who have seats reserved on a
			given flight
			<br> Produce a list of all flights for a given airport
			<br> Produce a list of all flights whose arrival and departure times
			are on-time/delayed
			<h3>For Customer Representative:</h3> Record a reservation <br>
			Add, Edit and Delete information for a customer <br>
			Produce customer mailing lists <br>
			Produce a list of flight suggestions for a given customer (based on that customer's past reservations)
			<h3>For Customer:</h3> Check reservations <br>
			Book a flight <br>
			Do auction <br>
			Get personalized flight suggestion list
			

		</div>
		<br>
		<h2>Wanna go for a <b>shot</b>?</h2>
		<br>
		<a href="index.jsp#search" class="btn btn-success btn-md">YEAH!</a>
	</div>
</body>
</html>